repository: sproogen/resume-theme
favicon: images/favicon.ico
version: 2
name: Valentin Bexa
title: Computer Science Student
email: valibexa@gmail.com
website: 'https://valentinbexa.com'
darkmode: false
twitter_username: valibexa
github_username: joacofrate00
instagram_username: valibexa
linkedin_username: valentin-bexa
about_profile_image: images/profile.jpg
about_content: >
  Hi, my name's Valentin and I'm a Computer Science Student, currently based in
  Arad, Romania. I enjoy learning and working with computers and especially
  tinkering with Virtual Machines and Operating Systems. My experience as an IT
  instructor helped with my communication skills as well as helping me become a
  better person and leader.

  I am most skilled in: <mark>Linux</mark> and <mark>Virtualization</mark>.
content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: AROBS Transilvania Software
        link: arobs.com
        sub_title: Embedded C - Internship
        caption: March 2022 - May 2022
        quote: ''
        description: >
          The automotive industry is constantly growing and cars are getting
          increasingly more tech-focused which means a lot of programmers and
          developers are needed. This is what helped me discover AROBS and their
          Embedded C Internship program. During this internship I learned a lot
          of techincal skills, such as how <mark>Git</mark> works and how
          effectiv proper teamwork is.
      - layout: left
        title: Logiscool
        link: logiscool.com
        sub_title: IT and Robotics Instructor
        caption: September 2020 - Present
        quote: ''
        description: >
          A lot of children nowadays get increasingly curious about how
          computers work and especially how their favorite games work. This is
          where I step in, working as an IT Instructor, I helped teach children
          how computers work and think, helping them think mathematically and
          logically. Logiscool also offers a Robotics course which I also
          taught, it based on Lego Mindstorms and coding in their proprietary
          platform. The children where taught using ScoolCode, a proprietary
          coding language based on Scratch and <mark>JavaScript</mark>.
      - layout: left
        title: Aquamar Solutions
        link: aquamarsolutions.ro
        sub_title: Website Administrator
        caption: February 2020 - February 2021
        quote: ''
        description: >
          Every company needs its websites properly administered and Aquamar
          Solutions is no exception. Keeping a retail company working is hard
          and I made sure the online part stayed up-to-date and working. During
          my time here I worked on 4 websites that were part of the company
          simultaneously, and learned a lot about WordPress and <mark>HTML5 +
          CSS</mark>.
  - title: Education
    layout: list
    content:
      - layout: left
        title: '"Aurel Vlaicu" University of Arad, Faculty of Exact Sciences'
        sub_title: 'Bachelor''s Applied Computer Science, taught in English'
        caption: 2020 - 2023
        quote: >
          "Aurel Vlaicu" University of Arad (ARACIS Certified) continues
          the tradition of university education in Arad that began here with the
          Institute of Theology (1822), the Faculty of Animal Husbandry and
          Veterinary Medicine (1947), the Institute of Sub-Engineers (1972).
        description: >
          During my time at Aurel Vlaicu University I learnt most of my key
          skills that have I have taken through my career such as teamwork and
          working to tight deadlines. I thouroughly enjoyed my time as
          university and learnt a lot about a healthy work life balance.
  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: Private VPN running on a VPS abroad
        quote: |
          This project was much more useful than I initally thought.
        description: >
          I started this project as a way of both learning how a
          <mark>VPS</mark> works and to delve deeper into <mark>bash
          shell</mark>. I have learned many skills through this and been I'm
          very proud of having this in my portfolio. The project is based on
          Algo VPN and runs flawlessly and fast enough to stream 4k video on
          multiple simultaneous devices.
  - title: A Little More About Me
    layout: text
    content: >
      Foreign language skills:

      - **English**: Comprehension, Reading, Writing, Speaking <mark>C2</mark>

      - **German**: Comprehension, Reading, Writing, Speaking <mark>A2</mark>



      Alongside my interests in Computers and Virtualization some of my other
      interests and hobbies are:

      - Cooking

      - Gaming

      - Computer Hardware Repairs

      - Drawing and the Arts
footer_show_references: true
remote_theme: sproogen/resume-theme
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-seo-tag
